apiVersion: batch/v1
kind: Job
metadata:
  name: test
spec:
  template:
    metadata:
      name: test
    spec:
      containers:
      - name: att-priors
        image: kundajelab/att-priors:latest
        args: ["bash", "/amtseng_ceph/att_priors/run_script.sh",
		      "-t", "/att_priors/TEAD4_test_2000.bed.gz",
              "-v", "/att_priors/TEAD4_test_2000.bed.gz",
              "-c", "/amtseng_ceph/att_priors/data/processed/ENCODE/config/TEAD4_config.json",
		      "-m", "/amtseng_ceph/att_priors/trained_models/TEST/",
		      "-p", "/amtseng_ceph/genomes/hg38.fasta", "/att_priors/",
		      "-p", "/amtseng_ceph/genomes/hg38.fasta.fai", "/att_priors/",
		      "-p", "/amtseng_ceph/att_priors/data/processed/ENCODE/tests/TEAD4_test_2000.bed.gz", "/att_priors/",
		      "dataset.reference_fasta=/att_priors/hg38.fasta",
		      "train.avg_class_loss=True",
		      "train.att_prior_loss_weight=1"]
        resources:
          requests:
            cpu: "20"
            memory: 32Gi
            nvidia.com/gpu: 1
          limits:
            cpu: "30"
            memory: 64Gi
            nvidia.com/gpu: 1
        volumeMounts:
        - mountPath: /amtseng_ceph
          name: amtseng-ceph
      restartPolicy: Never
      volumes:
        - name: amtseng-ceph
          flexVolume:
            driver: ceph.rook.io/rook
            fsType: ceph
            options:
              clusterNamespace: rook
              fsname: nautilusfs
              path: /amtseng
              mountUser: amtseng
              mountSecret: ceph-fs-secret
  backoffLimit: 3
