apiVersion: v1
kind: Pod
metadata:
  name: att-priors
spec:
  containers:
  - name: att-priors
    image: kundajelab/genome-pytorch-sacred:nautilus
    imagePullPolicy: Always
    resources:
      requests:
        cpu: 2
        memory: 7Gi
      limits:
        cpu: 2
        memory: 7Gi
    command:
    - /bin/bash
    - -c
    args:
    - sleep infinity
    volumeMounts:
    - mountPath: /ceph
      name: ceph
  volumes:
    - name: ceph
      flexVolume:
        driver: ceph.rook.io/rook
        fsType: ceph
        options:
          clusterNamespace: rook
          fsname: nautilusfs
          path: /amtseng
          mountUser: amtseng
          mountSecret: ceph-fs-secret
