apiVersion: v1
kind: Pod
metadata:
  name: att-priors
spec:
  containers:
  - name: att-priors 
    image: kundajelab/att-priors:latest
    args: ["sleep", "infinity"]
    volumeMounts:
    - mountPath: /amtseng_ceph
      name: amtseng-ceph
  volumes:
    - name: amtseng-ceph
      flexVolume:
        driver: ceph.rook.io/rook
        fsType: ceph
        options:
          clusterNamespace: rook
          fsname: nautilusfs
          path: /amtseng
          mountUser: amtseng
          mountSecret: ceph-fs-secret
