apiVersion: batch/v1
kind: Job
metadata:
  name: test
spec:
  template:
    spec:
      containers:
      - name: test-cont
        image: kundajelab/genome-pytorch-sacred:gcp
        imagePullPolicy: Always
        resources:
          requests:
            memory: 10Gi
            cpu: 1
          limits:
            memory: 16Gi
            cpu: 3
        command:
        - "/bin/bash"
        - "-c"
        - "python --version; sleep 10000"
      restartPolicy: Never
  backoffLimit: 0
